### ISSUE TITLE
Port v1 to v2 - ENTMQ-873

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-wiki#11]
Seems like a candidate to port. So the three remembers its state if being updated.

[ENTMQ-873] Preserve expand/collapse status of jmx/activemq tree

**Comment by davsclaus** [comment]
The fix on V1 is a clever hack in dynatree. As v2 is newer libraries etc, I wonder where we are today with this. Also need to verify the issue on v2 if its still there.

**Comment by gashcrumb** [comment]
Ah, we should move that clever hack over :-)  We've actually kept the same version of dynatree and jquery-ui, so the fix would still be applicable.

**Comment by davsclaus** [comment]
Okay have reproduced this on v2, when creating a new queue or topic etc then the tree redraws - though there is some logic to force that to happen

$scope.workspace.loadTree();

**Comment by davsclaus** [comment]
This seems not relevant in v2 as after deleting a queue it selects the queue folder already. And for purge it stays.
