### ISSUE TITLE
Consider disabling or moving some plugins outside so we have a core set

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-wiki#13]
We can consider moving out some wiki plugins to another repo so we have a core set of plugins in hawtio-wiki. The idea is to strip out unwanted plugins that we dont really need and also help trim down the .js size of this plugin.

**Comment by gashcrumb** [comment]
Agreed.  I kinda think the camel/activemq plugins would be better suited in hawtio-jmx, really hawtio-jmx could be a collection of Java related tech.  Right now they're in the wiki since there's dependencies in the code, but maybe that could be reworked a bit...

**Comment by davsclaus** [comment]
@jstrachan this is the ticket about trimming some of the unwanted plugins.

**Comment by davsclaus** [comment]
I think the wiki dependency was for the Camel route editor, which we wont need for the fabric8 releases.

So yeah maybe a good idea to move java plugins to hawtio-jmx, and then leave wiki for the wiki + the camel route editor (if we want to keep it around?)

**Comment by davsclaus** [comment]
So the list of essential Java related plugins we would need to support for fabric8 would be
- activemq
- camel
- and what comes out of the box in hawtio-jmx

Today in hawtio-wiki we have additonal
- docker-registry
- dozer
- fabric 1.x (dummy there is no code)
- git
- karaf
- maven
- osgi
- wiki

**Comment by davsclaus** [comment]
Now we may consider supporting osgi + karaf as essential as well?
- activemq
- camel
- and what comes out of the box in hawtio-jmx
- karaf
- osgi

For karaf I would like to avoid the karaf terminal as it dont work well with the various karaf releses which they keep breaking it.

**Comment by davsclaus** [comment]
Though those plugins is middle-ware integration stuff, maybe a new hawtio module is better?

hawtio-integration

And then have integration / middleware java stuff there?

**Comment by jstrachan** [comment]
for the camel editor in the wiki; it'd be nice for that to work outside of the wiki too; e.g. inside Eclipse Orion using its back end to load/save the XML files

**Comment by jimmidyson** [comment]
Sounds like what we want is for hawtio-wiki to make it more pluggable. Some kind of hawtio-wiki-core & types contributed by plugins.

**Comment by davsclaus** [comment]
The new git repo is
https://github.com/hawtio/hawtio-integration

**Comment by davsclaus** [comment]
So the wiki plugin was a 932kb JS file. And the integration plugin is reduced to a 565 kb JS file.

**Comment by davsclaus** [comment]
@jimmidyson yeah we likely need a hawtio-wiki-core as we may want the plain wiki browser? Though I am not sure it works so well in hawtio v2 / fabric8 v2 to browse the quickstarts and whatnot.

**Comment by davsclaus** [comment]
We use wiki in the Library tab in the kube console. Though it does not looks so pretty.

![screen shot 2015-04-23 at 9 39 04 am](https://cloud.githubusercontent.com/assets/477100/7292452/304090ba-e99c-11e4-8893-5c2160fc77de.png)

**Comment by davsclaus** [comment]
Removed plugins from hawtio-wiki so we only have
- docker-registry
- dozer
- git
- maven
- wiki

I also had to remove the Camel wiki editor (temporary) until we find out a plugin system as @jimmidyson talk about allowing to plugin wiki extensions. 

Then dozer would also be possible to set free as its currently tied to wiki also.

I also removed the old fabric 1x which was not in use. There is still some spots left in the wiki that has scopes for profileId etc which is a fabric 1.x concept.

**Comment by davsclaus** [comment]
The wiki plugin is now reduced to a 268kb JS file.

**Comment by davsclaus** [comment]
The maven plugin has no use (yet) as we dont have the hawtio java server side with the mbean it needs to use for indexing and searching.

I wonder if we can move dozer + maven to a hawtio-java or hawtio-java-misc or some other name for various plugins that is java related. 

Then we can get the wiki to be just about wiki + git

**Comment by davsclaus** [comment]
Okay closing this now as I logged a ticket about the wiki plugins for editor extensions.
