### ISSUE TITLE
Camel plugin - The route metrics dont have the metrics library

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-wiki#4]
We have not ported this to v2.

Maybe there is a more awesome codehale metrics ui we can use instead?

![screen shot 2015-04-03 at 4 58 39 pm](https://cloud.githubusercontent.com/assets/477100/6983808/76e81bf2-da22-11e4-86ed-57158a7bee4b.png)

**Comment by davsclaus** [comment]
For example get it integrated with ES - it can report in JSon or JMX format

**Comment by gashcrumb** [comment]
We probably just need to copy the script over from 1.x for starters, will do that now...

**Comment by davsclaus** [comment]
Yay thanks Stan, it works. 

Though the CSS may need to be adjust a little - I can see if I can figure this out, but the metrics is there now.

![screen shot 2015-04-03 at 6 50 46 pm](https://cloud.githubusercontent.com/assets/477100/6985289/1604c92e-da32-11e4-8080-8dfe59bd7758.png)

**Comment by gashcrumb** [comment]
oh, didn't see that CSS file.  Let me bring that over also, one sec.

**Comment by gashcrumb** [comment]
Think this is more like it:

![hawtio wiki](https://cloud.githubusercontent.com/assets/351660/6985653/9a6d7316-da03-11e4-9249-216294e81ee7.png)
