### ISSUE TITLE
Continue porting Camel v1 to v2

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-wiki#5]
There is more work needed to be ported. The commit from 96c2f04255dcc1f13f01fd4293dec2c797406b56 on january 31st 2015 about showing properties for endpoints.

**Comment by davsclaus** [comment]
Yay the properties on the routes now work again and has all the new Camel 2.15 awesomeness.

![screen shot 2015-04-05 at 12 31 08 pm](https://cloud.githubusercontent.com/assets/477100/6996571/5afd6b54-db8f-11e4-8da8-f49ece73f957.png)

**Comment by davsclaus** [comment]
The endpoints has a little bug still - but we are almost there with all the ports

**Comment by gashcrumb** [comment]
Wow, awesome!

**Comment by davsclaus** [comment]
Just got the endpoint working again. It as a plugin -> plugins mistake ;)

![screen shot 2015-04-05 at 1 25 57 pm](https://cloud.githubusercontent.com/assets/477100/6996700/fc04e3b8-db96-11e4-8e7b-650c66b62ba0.png)

**Comment by jstrachan** [comment]
yay! :)
